export type EngineErrorCode =
	| "ROOM_HEALTH_BELOW_QUORUM"
	| "SEMANTIC_VALIDATION_FAILED"
	| "TURN_PARSE_FAILED"
	| "MAX_ROUNDS_EXCEEDED"
	| "INVALID_ROOM_ACTION"
	| "DUPLICATE_ISSUE";

export type StorageErrorCode =
	| "MIGRATION_FAILED"
	| "WRITE_CONFLICT"
	| "SNAPSHOT_CORRUPT"
	| "EVENT_LOG_APPEND_FAILED"
	| "LEDGER_READ_FAILED";

export type ProviderErrorCode =
	| "MODEL_NOT_FOUND"
	| "RATE_LIMITED"
	| "CONTEXT_TOO_LONG"
	| "TOOL_CALL_INVALID"
	| "PROVIDER_UNAVAILABLE";
